version: "3.9"
services:
  mongo:
    container_name: "nos-db"
    image: "mongo:latest"
    ports:
      - "27017:27017"
  nerdsopposesociety:
    image: nerdsopposesociety
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

