name: Backend CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  backend-ci:
    name: Run Backend Tests and Linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "npm"

      - name: Disable Husky installer
        run: npm pkg delete scripts.prepare

      - name: Install Node.js dependencies
        run: npm ci -w=backend

      - name: Run linter
        run: npm run lint -w=backend

      - name: Run build
        run: npm run build -w=backend

      - name: Run tests
        run: npm test -w=backend
