name: Frontend CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  frontend-ci:
    name: Run Frontend Tests and Linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: "npm"

      - name: Disable Husky installer
        run: npm set-script prepare ""

      - name: Install Node.js dependencies
        run: npm ci -w=frontend -w=backend

      - name: Run linter
        run: npm run lint -w=frontend

      - name: Run tests
        run: npm test -w=frontend

      - name: Run build
        run: npm run build -w=frontend
